// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopInspector.Infrastructure.Data;

#nullable disable

namespace ShopInspector.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopInspector.Core.Entities.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssetTypeID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetID");

                    b.HasIndex("AssetTypeID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetCheckList", b =>
                {
                    b.Property<int>("AssetCheckListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetCheckListID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("InspectionCheckListID")
                        .HasColumnType("int");

                    b.HasKey("AssetCheckListID");

                    b.HasIndex("AssetID");

                    b.HasIndex("InspectionCheckListID");

                    b.ToTable("AssetCheckLists");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetInspection", b =>
                {
                    b.Property<int>("AssetInspectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetInspectionID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionFrequencyID")
                        .HasColumnType("int");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ThirdParty")
                        .HasColumnType("bit");

                    b.HasKey("AssetInspectionID");

                    b.HasIndex("AssetID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("InspectionFrequencyID");

                    b.ToTable("AssetInspections");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetInspectionCheckList", b =>
                {
                    b.Property<long>("AssetInspectionCheckListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssetInspectionCheckListID"));

                    b.Property<int>("AssetCheckListID")
                        .HasColumnType("int");

                    b.Property<int>("AssetInspectionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetInspectionCheckListID");

                    b.HasIndex("AssetCheckListID");

                    b.HasIndex("AssetInspectionID");

                    b.ToTable("AssetInspectionCheckLists");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetType", b =>
                {
                    b.Property<int>("AssetTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetTypeID"));

                    b.Property<string>("AssetTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetTypeID");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyAdminEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.InspectionCheckList", b =>
                {
                    b.Property<int>("InspectionCheckListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionCheckListID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("InspectionCheckListDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionCheckListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionCheckListTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InspectionCheckListID");

                    b.ToTable("InspectionCheckLists");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.InspectionFrequency", b =>
                {
                    b.Property<int>("InspectionFrequencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionFrequencyID"));

                    b.Property<string>("FrequencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InspectionFrequencyID");

                    b.ToTable("InspectionFrequencies");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.InspectionPhoto", b =>
                {
                    b.Property<int>("InspectionPhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionPhotoID"));

                    b.Property<int>("AssetInspectionID")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("InspectionPhotoID");

                    b.HasIndex("AssetInspectionID");

                    b.ToTable("InspectionPhotos");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Asset", b =>
                {
                    b.HasOne("ShopInspector.Core.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetCheckList", b =>
                {
                    b.HasOne("ShopInspector.Core.Entities.Asset", "Asset")
                        .WithMany("AssetCheckLists")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopInspector.Core.Entities.InspectionCheckList", "InspectionCheckList")
                        .WithMany("AssetCheckLists")
                        .HasForeignKey("InspectionCheckListID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("InspectionCheckList");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetInspection", b =>
                {
                    b.HasOne("ShopInspector.Core.Entities.Asset", "Asset")
                        .WithMany("AssetInspections")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopInspector.Core.Entities.Employee", "Employee")
                        .WithMany("AssetInspections")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopInspector.Core.Entities.InspectionFrequency", "InspectionFrequency")
                        .WithMany("AssetInspections")
                        .HasForeignKey("InspectionFrequencyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");

                    b.Navigation("InspectionFrequency");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetInspectionCheckList", b =>
                {
                    b.HasOne("ShopInspector.Core.Entities.AssetCheckList", "AssetCheckList")
                        .WithMany("AssetInspectionCheckLists")
                        .HasForeignKey("AssetCheckListID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopInspector.Core.Entities.AssetInspection", "AssetInspection")
                        .WithMany("AssetInspectionCheckLists")
                        .HasForeignKey("AssetInspectionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetCheckList");

                    b.Navigation("AssetInspection");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Employee", b =>
                {
                    b.HasOne("ShopInspector.Core.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.InspectionPhoto", b =>
                {
                    b.HasOne("ShopInspector.Core.Entities.AssetInspection", "AssetInspection")
                        .WithMany("Photos")
                        .HasForeignKey("AssetInspectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetInspection");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Asset", b =>
                {
                    b.Navigation("AssetCheckLists");

                    b.Navigation("AssetInspections");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetCheckList", b =>
                {
                    b.Navigation("AssetInspectionCheckLists");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetInspection", b =>
                {
                    b.Navigation("AssetInspectionCheckLists");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.Employee", b =>
                {
                    b.Navigation("AssetInspections");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.InspectionCheckList", b =>
                {
                    b.Navigation("AssetCheckLists");
                });

            modelBuilder.Entity("ShopInspector.Core.Entities.InspectionFrequency", b =>
                {
                    b.Navigation("AssetInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
